name: CI Builds

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-python:
    name: Build Python
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Build Python
      run: poetry build

    - name: Install Python
      run: poetry install

    - name: Run Python Tests
      run: poetry run pytest -vv

    - name: Upload Python Distribution
      if: ${{ github.event_name == 'pull_request' || ( github.event_name == 'push' && ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') ) ) }}
      uses: actions/upload-artifact@v4
      with:
        name: dist-python-${{ matrix.python-version }}-${{ matrix.os }}
        path: dist/
